### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by pabloandrei** [logstash-plugins/logstash-output-elasticsearch#1061]
Hi, I need help from this group.
I'm using plugins to perform an extraction in the Oracle database, this extraction should be sent to Elasticsearch.

Logstash is running locally, via docker.
Elasticsearch is on Azure via ECK.

I access all ECK features through Ingress, both Elastic and Kibana.

But in Logstash is giving the error below...
**Log with ERROR:**
`logstash  | [2021-12-22T18:12:11,238][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@URL:80/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@URL:80/][Manticore::ClientProtocolException] SSL peer shut down incorrectly"}`

Anyone have any tips?

**My topology:**
![ELK-2-Page-1 drawio](https://user-images.githubusercontent.com/16004192/147144085-c5a2cb0e-2395-41ee-b393-34bc8ecdb3a4.png)

**My pipeline output:**
```
output {
    if "logstash-tempo-parado-total" in [tags] {
        elasticsearch {
            hosts => ["URL:80"]
            ssl => true
            ssl_certificate_verification => false
            user => "elastic"
            password => "????????"
            cacert => '/usr/share/logstash/etc/tls.crt'   
            index => "logstash-tempo-parado-total-%{+YYYY.MM}"            
        }
    }
}
```

- Version: 7.7.0
- Operating System: ubuntu on K8S (ECK)
- Config File:
```
version: "3"
services:
    logstash:
        image: docker.elastic.co/logstash/logstash:7.7.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - .\logstash:/usr/share/logstash/pipeline/
          - .\etc:/usr/share/logstash/etc/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork

networks:
    elknetwork:
        driver: bridge
```

**My Ingress config:**
![02](https://user-images.githubusercontent.com/16004192/147144405-244a6a3c-fbd1-4a79-bf79-fec1bb5e4be5.PNG)

Accessing using brower:
![01](https://user-images.githubusercontent.com/16004192/147144432-2ae2e448-00fd-4227-aaa8-487a36188c8a.PNG)
