### ISSUE TITLE
`ssl_certificate_verification` will not work without `ssl` being explicitly set

### ISSUE THREAD

**Issue by dandrestor** [logstash-plugins/logstash-output-elasticsearch#433]
This configuration:

```
elasticsearch {
  ...
  hosts => [ "https://something" ]
  ssl_certificate_verification => false
}
```

does not work. You need to explicitly add the parameter `ssl => true` for this to work as intended. However, the documentation [states](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-ssl) that if the parameter `ssl` is not set, then whatever protocol is specified in the `hosts` parameter will be used.

I believe the reason is that, in `http_client_builder.rb`, the function `self.setup_ssl` [returns](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/e18800936a913801a75fc564d4c18b930b15ba86/lib/logstash/outputs/elasticsearch/http_client_builder.rb#L66) if the parameter `ssl` is not set explicitly in the config file.

**Comment by dandrestor** [comment]
Another symptom is the error `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` when running with a self-signed certificate without specifying `ssl => true` explicitly.

**Comment by Petrox** [comment]
:+1: this issue is still open.

**Comment by whm0627** [comment]
the issue is in the core at https://github.com/logstash-plugins/logstash-mixin-http_client
I made a pull request, but not sure when that would get merged, cuz the latest tests failed before I made my push like 2 months ago.

for now, if you want a dirty fix, go to your local file: logstash/vendor/bundle/jruby/1.9/gems/logstash-mixin-http_client-5.2.1/lib/logstash/plugin_mixins/http_client.rb
and change it to the updated one:
https://github.com/whm0627/logstash-mixin-http_client/blob/master/lib/logstash/plugin_mixins/http_client.rb

after that, set `ssl_certificate_verification` to false

**Comment by jonassteinberg1** [comment]
currently have same error:

[Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}

**Comment by Eschon** [comment]
I have a similar issue. I have both `ssl => true` and `ssl_certificate_verification => false` setin my configuration but I still get the error:

```
[Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}
```

**Comment by edermariano** [comment]
I have the same issue of you @Eschon.

**Comment by rjulian** [comment]
Running into the same issue as @Eschon . Ever get any sort of workaround for the issue?

**Comment by Eschon** [comment]
I was able to work around the issue but I'm not sure if my workaround will help you.  
It was setting up the SSL certificate so that it could be verified.

**Comment by laurfx** [comment]
You need the same syntax to work, you can put the .pem from Search Guard for example , esnode.pem

output {
      elasticsearch {
        user => logstash
        password => xxx
        hosts => [ "https://l1807s.sss.se.scania.com:9200/" ]
        index => "logstash-flex-%{+YYYY.MM.dd}"
        cacert => "/opt/logstash-2.3.1/ScaniaRootCA02.cer"
      }
}

**Comment by eedugon** [comment]
Per @jakelandis  request, I'm writing a non-working use case related to this issue:

In logstash 5.1.2... If elasticsearch is using a wildcard + self signed cerfificate, then ssl_certificate_verification: false is failing and raising an execption and the only way to avoid it is providing the CA with the cacert option.

The error looks like this:
```
2018-01-23T21:46:37,271][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTPS:0x18c0fa1b URL:https://~hidden~:~hidden~@FQDN-omitted:9200>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://~hidden~:~hidden~@fqdn...:9200][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"} 
```
In this use case, ssl_certificate_verification: False works for example if we access the server via IP and not FQDNs, but not if we wan't to skip the CA validation.

I suspect skip verification works for "hostname match CN" but it crashes in the "CA cert not trusted" case here.

**Comment by inqueue** [comment]
Elastic Cloud Enterprise uses a wildcard self-signed certificate. Configuring `ssl_certificate_verification => false` with an ECE ES cluster is effectively broken.

**Comment by jsvd** [comment]
This should no longer happen for quite some time, as the plugin checks if any of the hosts in the hosts list has the https schema and enables ssl: https://github.com/logstash-plugins/logstash-output-elasticsearch/blame/353e4f580c89292105611b1a7720e6bb1f1d1100/lib/logstash/outputs/elasticsearch/http_client_builder.rb#L106

I tested manually now and confirmed that I could connect and send data to the wrong host by setting `ssl_certificate_verification => false `.

For example, I created a certificate for cn=node01 but set my logstash's pipeline to the following:

```
input { stdin {} }
output {
  elasticsearch {
    hosts => [ "https://localhost:9200" ]
    user => my_user
    password => XXXX
  }
}
```

This raised an error:

```
[2018-06-06T17:07:06,847][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://my_user:xxxxxx@localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://my_user:xxxxxx@localhost:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}
```

However adding `ssl_certificate_verification => false`:

```
input { stdin {} }
output {
  elasticsearch {
    hosts => [ "https://localhost:9200" ]
    user => my_user
    password => XXXX
    ssl_certificate_verification => false
  }
}
```

Made it work correctly:

```
[2018-06-06T17:10:14,092][WARN ][logstash.outputs.elasticsearch] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2018-06-06T17:10:14,740][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://my_user:xxxxxx@localhost:9200/]}}
[2018-06-06T17:10:14,772][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://my_user:xxxxxx@localhost:9200/, :path=>"/"}
[2018-06-06T17:10:15,406][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"https://my_user:xxxxxx@localhost:9200/"}
[2018-06-06T17:10:15,520][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>6}
[2018-06-06T17:10:15,528][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
```

**Comment by CCoruble** [comment]
Hello,

Problem still unresolved in logstash 7.1.1

Conf:
`input{
  gelf{
    id => "1"
    host => "127.0.0.1"
    port => 12201
  }
}
output {
  elasticsearch{
    hosts => ["https://my_elasticsearch:9200"]
    index => ["my_index"]
    ssl_certificate_verification => false
  }
}
`
Result:
`"Elasticsearch Unreachable: [https://my_elasticsearch:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}`

**Comment by EdgeSync** [comment]
After a lot of googling, and reading through so much documentation - finally found myself here. Same issue persisting for me.

**OS:**
Debian 9 x64

**Kernel:** 
4.9.0-11-amd64

**Java Version:** 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Logstash Version:** 
logstash 7.4.1


**logstash working conf example:**

```
input { 
  udp  {
    port => 10000
    codec => json
  }
}
filter { }
output {
  elasticsearch {
    hosts => ["https://1.2.4.5:9200"]
    user => "logstash_internal"
    password => "some-password-here"
    cacert => "/etc/logstash/conf.d/my_elastic_ca.cer"
    ssl_certificate_verification => false
    index => "some_index"
  }
}
```

**Comment by Djeezus** [comment]
Could it be that the "proxy" directive is (again) ignored ?  I also tried the previous suggestions mentioned here, verification false and such ....
When using the "proxy_url" in Filebeat's output.elasticsearch section, the data arrives at the ES instance just fine, so I know it's not the proxy itself :)

**OS:**
Windos 10 Enterprise

**Java Version:**
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode, sharing)

**Logstash Version:**
logstash 7.6.0

**Relevant logstash config**

>         elasticsearch { 
>			hosts => ["https://somehost:9243"] 
>			proxy => "http://127.0.0.1:3128" 
>			index => "apache-accesslogs-%{+yyyy.MM.dd}"
>			user => "blah"
>			password => "xxxxxxxx"
>			ssl_certificate_verification => false
>			cacert => "C:\here\ece_elastic.cer"
>		}

And this is what's begin logged continuously with --log.level=debug :

`[2020-02-12T15:34:50,688][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://blah:xxxxxx@somehost:9243/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://blah:xxxxxx@somehost:9243/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}`

**Comment by steve21168** [comment]
Still not fixed in 7.6.0....
`ssl_certificate_verification => false`
 Same error:
`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by tomqwu** [comment]
Come one, wasted me a day to resolve this issue, can't you document or fix it, it's 2020 now.

**Comment by tsquillario** [comment]
Agree. Setting `ssl_certificate_verification => false` should remove the WARN message from the logs.

**Comment by sri53** [comment]
I am facing this issue in 2020

**Comment by msvechla** [comment]
Same issue for me, using logstash docker image `docker.elastic.co/logstash/logstash:7.5.0`.

Output:
```
output {
    elasticsearch {
        hosts                        => ["${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
        index                        => "${ELASTIC_INDEX}_writealias"
        timeout                      => 120
        user                         => "${ELASTICSEARCH_USERNAME}"
        password                     => "${ELASTICSEARCH_PASSWORD}"
        ssl                          => true
        ssl_certificate_verification => false
    }
}
```

logstash logs:

```
[2020-04-23T10:13:23,780][WARN ][logstash.runner          ] SIGHUP received.
[2020-04-23T10:13:25,653][INFO ][org.reflections.Reflections] Reflections took 62 ms to scan 1 urls, producing 20 keys and 40 values 
[2020-04-23T10:13:29,176][WARN ][logstash.outputs.elasticsearch] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2020-04-23T10:13:29,929][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elastic:xxxxxx@efk-es-http.monitoring:9200/]}}
[2020-04-23T10:13:30,557][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@efk-es-http.monitoring:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@efk-es-http.monitoring:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}
```

As you can see from the output the `ssl_certificate_verification` option definitely is recognized, however we still get certificate errors.

**Comment by eedugon** [comment]
@jsvd : I believe this isn't really fixed, as certificate verification: false is only bypassing the verification of the hostname and not bypassing the verification of the CA, which is what the majority of people expects if a generic `certificate verification` is set to false.

**Comment by andrewmichaelsmith** [comment]
Same issue here - I'm using the [Elasticsearch Operator](https://www.elastic.co/blog/introducing-elastic-cloud-on-kubernetes-the-elasticsearch-operator-and-beyond) to run an ES cluster but I can't get logstash to connect because (it seems) the CA is not verified.

Have tried `ssl => true` and setting a dummy CA with `cafile` but no luck, same error.

**Comment by turbopape** [comment]
Still having the same issue :(

**Comment by Lasim** [comment]
same here.

**Comment by xirius** [comment]
Same here.

**Comment by hetalsonavane** [comment]
Still having the issue

**Comment by coreyperkins** [comment]
same issue....

**Comment by srikwit** [comment]
same issue 7.9.1

**Comment by meiry** [comment]
still  with docker.elastic.co/logstash/logstash:7.10.1
but what should i configure if i dont want to use SSL ,

**Comment by jasonneurohr** [comment]
We are spinning up ECK in a dev environments for testing etc. and don't want to get bogged down with proper certs until we move to higher level environments. The fact that ssl_certificate_verification doesn't 'fully' disable verification is a bit misleading and doesn't give us a path forward short of using certificates issued from a real CA even in development.

What do we need to do to get some traction on this issue!

**Comment by uday-accel** [comment]
facing same issue in 2021

**Comment by uday-accel** [comment]
Thanks @meiry I did the same few mins back. Thanks for documenting it :)

**Comment by DanielHabenicht** [comment]
@meiry which yaml are you editing? 

I got it working in kubernetes with the following config: 
The key is to provide a cert file.
```yaml
{{- $elasticsearch := "<your-elasticsearch-domain" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: extractor-rss-config
        - name: cert
          emptyDir: {}
      containers:
        - name: {{ $fullName }}
          image: "docker.elastic.co/logstash/logstash-oss:7.12.0" # 
            - name: ELASTIC_API_ROOT
              value: "https://{{$elasticsearch}}:443"
            - name: ELASTIC_INDEX_NAME
              value: "test-index"
          envFrom:
            - secretRef:
                name: elasticsearch                               
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: cert
              mountPath: /usr/share/logstash/cert
      initContainers:
        - name: install
          image: nginx
          command:
              [
                '/bin/bash',
                '-c',
                "echo -n | openssl s_client -connect {{$elasticsearch}}:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./cert/ca_logstash.cer",
              ]
          volumeMounts:
          - name: cert
            mountPath: "/cert"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extractor-rss-config
  namespace: default
data:
  logstash.conf: |
    input {
      rss {
          id => "rss2"
          url => "https://news.microsoft.com/feed/"
          interval => 7200
      }
    }

    output {
        elasticsearch {
            hosts => ["${ELASTIC_API_ROOT}"]
            index => "${ELASTIC_INDEX_NAME}"
            document_id => "%{fingerprint}"
            user => "${ELASTIC_API_USERNAME}"
            password => "${ELASTIC_API_PASSWORD}"
            ssl_certificate_verification => "false"
            cacert => "/usr/share/logstash/cert/ca_logstash.cer"
        }
        stdout {
            codec => rubydebug
        }
    }
```
